#!/bin/sh 
# 
# script to bring up the tun/tap device in in bridged mode 
# first parameter is name of tap device (e.g. tap0)
#
# some constants specific to the local host - change to suit your host
#
if [ -z "$*" ]; then echo "Usage esp32-ifup tap0 eth0";exit 1; fi
ETH0IPADDR=192.168.0.3
MASK=255.255.255.0
GATEWAY=192.168.0.1
BROADCAST=192.168.0.255
#
# First take eth0 down, then bring it up with IP address 0.0.0.0 
#
/sbin/ifdown $2
/sbin/ifconfig $2 0.0.0.0 promisc up
#
# Bring up the tap device
#
#/usr/sbin/openvpn --mktun --dev $1 --user `id -un`
ip tuntap add dev $1 mode tap user `id -un`
/sbin/ifconfig $1 0.0.0.0 promisc up
#
# create the bridge between eth0 and the tap device
#
/usr/sbin/brctl addbr br0
/usr/sbin/brctl addif br0 $2
/usr/sbin/brctl addif br0 $1
# 
# only a single bridge so loops are not possible, turn off spanning tree protocol
#
/usr/sbin/brctl stp br0 off 
# 
# Bring up the bridge with ETH0IPADDR and add the default route 
#
/sbin/ifconfig br0 $ETH0IPADDR netmask $MASK broadcast $BROADCAST
/sbin/route add default gw $GATEWAY
#
# stop firewall - comment this out if you don't use Firestarter
#
#/sbin/service firestarter stop
# Make sure packages are forwarded

iptables -I FORWARD -m physdev --physdev-is-bridged -j ACCEPT

sysctl net.ipv4.ip_forward=1

