#!/bin/sh 
# 
# Script to bring down and delete bridge br0 when QEMU exits 
# 
# Bring down eth0 and br0 
#
if [ -z "$*" ]; then echo "Usage esp32-ifdown tap0 eth0";exit 1; fi
/sbin/ifdown $2
/sbin/ifdown br0
/sbin/ifconfig br0 down 
# 
# Delete the bridge
#
/usr/sbin/brctl delbr br0 
# 
# bring up eth0 in "normal" mode 
#
/sbin/ifconfig $2 -promisc
/sbin/ifup $2 
#
# delete the tap device
#
#/usr/sbin/openvpn --rmtun --dev $1
ip tuntap del dev $1 mode tap

#
# start firewall again
# 
#/sbin/service firestarter start 
